package com.example.petmanagement.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents an Address entity in the system.
 * This class is mapped to the "address" table in the database.
 * It contains details about the address such as city, type, name, and number.
 */
@Entity
@Table(name = "address")
@Getter
@Setter
public class Address extends Auditable {

    /**
     * The unique identifier for the address.
     * It is auto-generated using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The city where the address is located.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private String city;

    /**
     * The type of the address, e.g., road, street, avenue.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private String type;

    /**
     * The name of the address, e.g., the name of the street or avenue.
     * This field is mandatory.
     */
    @Column(name = "address_name", nullable = false)
    private String addressName;

    /**
     * The number of the address, e.g., house or building number.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private String number;

    // Constructors, equals, hashCode would be generated by Lombok
}